version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - abmlevel
  - adwaita
  - akahitoha
  - alsa
  - amdgpu
  - antfu
  - atuin
  - autopower
  - bibata
  - binfmt
  - blueplanet
  - bluestar
  - btrfs
  - cachix
  - catppuccin
  - centisecs
  - charliermarsh
  - clinfo
  - coredump
  - correcthorsebatterystaple
  - creds
  - cryptroot
  - cuda
  - dbaeumer
  - dconf
  - dearmor
  - denoland
  - dependi
  - difftastic
  - direnv
  - disko
  - fastfetch
  - fcitx
  - felixc
  - fetchurl
  - fontconfig
  - gamemode
  - gamescope
  - ghostty
  - gltf
  - gpasswd
  - GPGPU
  - huggingface
  - ideapad
  - initstate
  - inshellisense
  - jnoortheen
  - kexec
  - keyrings
  - kobuk
  - kptr
  - lavd
  - lazydocker
  - libmfx
  - libstdc
  - libva
  - libvpl
  - libze
  - logicalmonitor
  - loglevel
  - mdns
  - mergiraf
  - mimeapps
  - moegirl
  - monaspace
  - Monaspice
  - monitorspec
  - mozc
  - netdev
  - networkmanager
  - newgrp
  - nixd
  - nixfmt
  - nixos
  - nixpkgs
  - NOFILE
  - noto
  - numtide
  - nushell
  - ocloc
  - ollama
  - oneapi
  - oneshot
  - opencl
  - openpgp
  - optimise
  - paperwm
  - papirus
  - pipewire
  - pipx
  - pkgs
  - powertop
  - printk
  - ptes
  - qdisc
  - ramalama
  - ratemode
  - rcutree
  - rmem
  - rocm
  - rtkit
  - rustscheds
  - ryzenadj
  - sched
  - setvars
  - sn0wm1x
  - stdenv
  - substituters
  - subvolume
  - sycl
  - timesyncd
  - trytriplex
  - unifiedjs
  - unocss
  - usermod
  - userns
  - vainfo
  - virtualisation
  - wmem
  - writeback
  - XMODIFIERS
  - zhwiki
  - zram
ignoreWords: []
import: []
